### ISSUE TITLE
Evilcraft Vengeance spirits

### ISSUE THREAD

**Issue by RadicalInquisitor** [zeeshell/The-Kitchen-Sink#1]
Temporary warp applied by spirits should be removed in the evilcraft configs via

 B:general.thaumcraftVengeanceSpiritWarp= set to false

or disabled entirely via

I:vengeanceSpirit.spawnLimit= set to 0

They damage gameplay considerably due to the nature of their spawning

**Comment by zeeshell** [comment]
Fixed with commit dc23f14
